(define (problem problema_llibres)
  (:domain domini_llibres)
  (:objects A B B1 B2 B3 B4 C D E F G H - llibre 
            gener febrer març abril maig juny juliol agost setembre octubre novembre desembre - mes)
  (:init 
        (= (mes_sumatori) 0)
        (= (mes gener) 1)
        (= (mes febrer) 2)
        (= (mes març) 3)
        (= (mes abril) 4)
        (= (mes maig) 5)
        (= (mes juny) 6)
        (= (mes juliol) 7)
        (= (mes agost) 8)
        (= (mes setembre) 9)
        (= (mes octubre) 10)
        (= (mes novembre) 11)
        (= (mes desembre) 12)

        (predecessor gener febrer)
        (predecessor febrer març)
        (predecessor març abril)
        (predecessor abril maig)
        (predecessor maig juny)
        (predecessor juny juliol)
        (predecessor juliol agost)
        (predecessor agost setembre)
        (predecessor setembre octubre)
        (predecessor octubre novembre)
        (predecessor novembre desembre)
        ;(predecessor desembre gener)
      
        (llegit A)
        (mes_lectura A gener)
      
        (predecessor A B)
        (predecessor A B1)
        (predecessor B1 B2)
        (predecessor B2 B3)
        
        (paralel B B4)
        (paralel B4 B)
        (paralel B B1)
        (paralel B1 B)
        (paralel B1 B4)
        (paralel B4 B1)

        (predecessor B C)
        ;(predecessor B1 C)
        ;(predecessor B2 C)
        (predecessor B3 C)
        (predecessor B4 C)
        (predecessor C D)
        (predecessor D E)
        (predecessor E F)
        (predecessor F G)
        (predecessor G H)
  )

  (:goal (llegit H))
  (:metric minimize (mes_sumatori))
)