(define (problem time_growth_problem6) 
 (:domain domini_llibres) 
 (:objects gener febrer marc abril maig juny juliol agost setembre octubre novembre desembre - mes 
           a b c d e f g h i j k l m n o p q r s t u v w x y z { \ ] ^ _ ` a b c d e f g h - llibre) 
 (:init 
  (= (mes_sumatori) 0) 
  (= (mes gener) 1) 
  (= (mes febrer) 2) 
  (= (mes marc) 3) 
  (= (mes abril) 4) 
  (= (mes maig) 5) 
  (= (mes juny) 6) 
  (= (mes juliol) 7) 
  (= (mes agost) 8) 
  (= (mes setembre) 9) 
  (= (mes octubre) 10) 
  (= (mes novembre) 11) 
  (= (mes desembre) 12) 


  (predecessor f v) 
  (predecessor _ h) 
  (predecessor d _) 
  (predecessor u c) 
  (predecessor b z) 
  (predecessor a p) 
  (predecessor z e) 
  (predecessor k d) 
  (predecessor a e) 
  (predecessor a c) 
  (predecessor r ^) 
  (predecessor b o) 
  (predecessor _ b) 
  (predecessor v {) 
  (predecessor m g) 
  (predecessor z m) 
  (predecessor ` z) 
  (predecessor e _) 
  (predecessor m ^) 
  (predecessor _ c) 
  (predecessor e z) 
  (predecessor d b) 
  (predecessor m t) 
  (predecessor h a) 
  (predecessor u g) 
  (predecessor f g) 
  (predecessor { d) 
  (predecessor h f) 
  (predecessor g u) 
  (predecessor b b) 
  (predecessor t p) 
  (predecessor ] {) 
  (predecessor k h) 
  (predecessor p f) 
  (predecessor t c) 
  (predecessor g a) 

  (= (pag_mes gener) 0) 
  (= (pag_mes febrer) 0) 
  (= (pag_mes marc) 0) 
  (= (pag_mes abril) 0) 
  (= (pag_mes maig) 0) 
  (= (pag_mes juny) 0) 
  (= (pag_mes juliol) 0) 
  (= (pag_mes agost) 0) 
  (= (pag_mes setembre) 0) 
  (= (pag_mes octubre) 0) 
  (= (pag_mes novembre) 0) 
  (= (pag_mes desembre) 0) 

  (= (pagines a) 400) 
  (= (pagines b) 400) 
  (= (pagines c) 400) 
  (= (pagines d) 400) 
  (= (pagines e) 400) 
  (= (pagines f) 400) 
  (= (pagines g) 400) 
  (= (pagines h) 400) 
  (= (pagines i) 400) 
  (= (pagines j) 400) 
  (= (pagines k) 400) 
  (= (pagines l) 400) 
  (= (pagines m) 400) 
  (= (pagines n) 400) 
  (= (pagines o) 400) 
  (= (pagines p) 400) 
  (= (pagines q) 400) 
  (= (pagines r) 400) 
  (= (pagines s) 400) 
  (= (pagines t) 400) 
  (= (pagines u) 400) 
  (= (pagines v) 400) 
  (= (pagines w) 400) 
  (= (pagines x) 400) 
  (= (pagines y) 400) 
  (= (pagines z) 400) 
  (= (pagines {) 400) 
  (= (pagines \) 400) 
  (= (pagines ]) 400) 
  (= (pagines ^) 400) 
  (= (pagines _) 400) 
  (= (pagines `) 400) 
  (= (pagines a) 400) 
  (= (pagines b) 400) 
  (= (pagines c) 400) 
  (= (pagines d) 400) 
  (= (pagines e) 400) 
  (= (pagines f) 400) 
  (= (pagines g) 400) 
  (= (pagines h) 400) 

  (per_llegir e) 
  (per_llegir \) 
  (per_llegir l) 
  (per_llegir g) 
 ) 

 (:goal  (forall (?l - llibre) 
   (not (per_llegir ?l)) 
  ) 
 ) 
)